vich_uploader:
    db_driver: orm

    mappings:
        backgrounds:
            uri_prefix: /backgrounds
            upload_destination: '%kernel.project_dir%/public/backgrounds'
            # Will rename uploaded files using a uniqueid as a prefix.
            namer: Vich\UploaderBundle\Naming\OrignameNamer
        images:
            uri_prefix: /images
            upload_destination: '%kernel.project_dir%/public/images'
            # Will rename uploaded files using a uniqueid as a prefix.
            namer: Vich\UploaderBundle\Naming\OrignameNamer

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
